import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Header from "./ui/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    template: '%s | NextJS TODO',
    default: "Next TODO",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <footer className="footer mt-10">Footer Section</footer>
      </body>
    </html>
  );
}
