import { Metadata } from "next";
import Link from 'next/link';

import { Inter } from "next/font/google";
import "./globals.css";

import Header from "@/app/ui/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    template: '%s | NextJS TODO',
    default: "Next TODO",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  auth
}: {
  children: React.ReactNode
  auth: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <nav>
        <Link href="/login">Open modal</Link>
      </nav>
        {children}
        <div>{auth}</div>
        <footer className="footer mt-10">Footer Section</footer>
      </body>
    </html>
  );
}
